package Practice;

class Human
{
    private int age;
    private String name;
    /* 
    //it is accessible because the variable is private and the following method getAge() is in the same class Human
    //Getter 
    public int getAge()
    {
        return age;
    }
    //Setter
    public void setAge(int a)
    {   
        age = a;
    }
    */

    //Constructor
    public Human()//Default Constructor/Normal Constructor
    {
        age = 21;
        name = "John";
    }

    public Human(int a, String n) //Parameterized Constructor
    {
        age = a;
        name = n;
    }
    //Autogenerated by the ide's source action
    public int getAge() {
        return age;
    }
    public void setAge(int age) {
        this.age = age;
    }
    //it is accessible because the variable is private and the following method getName() is in the same class Human
    //Getter
    public String getName()
    {
        return name;
    }
    //Setter
    public void setName(String n)
    {
        name = n;
    }
}

public class Demo {
    public static void main(String[] args)
    {
        Human obj = new Human();
        Human obj1 = new Human(21,"Nitish");
        System.out.println(obj.getName() + ": " + obj.getAge());
        System.out.println(obj1.getName() + ": " + obj1.getAge());
        // obj.setAge(21);
        // obj.setName("Sarweshwaran");
        //System.out.println(obj.getName()+": "+obj.getAge());
    }    
}
